# @package _global_

defaults:
  - ../env: bigym/move_plate
  - ../method: act

demos: 60
num_pretrain_steps: 0
num_pretrain_epochs: 1000
eval_every_steps: 0
eval_every_epochs: 100
num_train_frames: 0
num_eval_episodes: 50
batch_size: 128
save_snapshot: false
snapshot_every_n: 0
replay_size_before_train: 500

pixels: true
visual_observation_shape: [256, 256]
frame_stack: 1

is_imitation_learning: true

action_repeat: 1
action_sequence: 20
execution_length: 20
temporal_ensemble: true
use_standardization: true
use_min_max_normalization: false
min_max_margin: 0
norm_obs: true
obs_norm_type: standardization

update_every_steps: 1
log_eval_video: false
save_csv: true

env:
  demo_alignment: reference_post_action

replay:
  nstep: 1
  num_workers: 0
  epoch_style_sampling: true
  persist: false
  cache_frozen_image_features: false

wandb:
  use: false
  project: act_bigym
  name: move_plate_act_1000epochs

hydra:
  run:
    dir: ./exp_local/bigym_move_plate_act_direct15d_refparams_${now:%Y%m%d%H%M%S}
