# @package _global_
action_sequence: 20

method:
  name: act
  is_rl: false
  lr: 1e-5
  weight_decay: 1e-4
  lr_backbone: 1e-5
  num_train_steps: ${num_pretrain_steps}
  adaptive_lr: false
  actor_grad_clip: 1.0
  noise_mask_steps: 0
  repeat_action: false
  use_lang_cond: true

  actor_model:
    type: transformer
    hidden_dim: 256
    enc_layers: 4
    dec_layers: 6
    dim_feedforward: 2048
    dropout: 0.1
    nheads: 8
    num_queries: ${action_sequence}
    pre_norm: false
    data_augmentation: true
    use_lang_cond: ${method.use_lang_cond}

  encoder_model:
    type: resnet
    model: resnet18

  view_fusion_model:
    type: multicam_feature
    mode: flatten
