# @package _global_

method:
  name: bc
  is_rl: false
  lr: 1e-4
  num_train_steps: ${num_pretrain_steps}
  adaptive_lr: true
  actor_grad_clip: null

  actor_model:
    type: mlp_bottleneck_sequence
    num_rnn_layers: 1
    rnn_hidden_size: 128
    keys_to_bottleneck: []
    bottleneck_size: 50
    norm_after_bottleneck: true
    tanh_after_bottleneck: true
    hidden_dims: [1024, 1024]
    output_sequence_network_type: rnn
    output_sequence_length: ${action_sequence}

  encoder_model:
    type: resnet
    model: resnet18

  view_fusion_model:
    type: multicam_feature
    mode: flatten
