# @package _global_

method:
  name: cqn_official
  _target_: robobase.method.cqn.CQN
  is_rl: true
  num_train_steps: ${num_train_frames}
  num_explore_steps: ${num_explore_steps}
  critic_lr: 1e-4
  weight_decay: 0.0
  critic_target_tau: 0.02
  critic_grad_clip: null
  levels: 3
  bins: 5
  atoms: 51
  v_min: 0.0
  v_max: 200.0
  critic_lambda: 1.0
  centralized_critic: false
  use_dueling: true
  always_bootstrap: false
  stddev_schedule: "0.1"
  bc_lambda: 0.0
  bc_margin: 0.0
  use_target_network_for_rollout: false
  num_update_steps: 1

  model:
    hidden_dims: [512, 512]
    activation: silu
    norm: layer
    linear_bias: false

  encoder_model:
    type: resnet
    model: resnet18
    trainable: true
    pretrained: false
    use_plucker: false

  view_fusion_model:
    type: multicam_feature
    mode: flatten
