# @package _global_
action_sequence: 20

method:
  name: diffusion
  is_rl: false
  lr: 1e-4
  num_train_steps: ${num_pretrain_steps}
  num_diffusion_iters: 100
  adaptive_lr: true
  actor_grad_clip: null
  use_ema: false
  ema_decay: 0.9999
  weight_decay: 1.0e-6
  noise_mask_steps: 0
  repeat_action: false

  actor_model:
    type: conditional_unet1d
    sequence_length: ${action_sequence}
    diffusion_step_embed_dim: 256
    down_dims: [256, 512, 1024]
    kernel_size: 5
    n_groups: 8

  encoder_model:
    type: resnet
    model: resnet18

  view_fusion_model:
    type: multicam_feature
    mode: flatten
